package com.pratyaksh.iykyk.ui.theme

import androidx.compose.ui.graphics.Color

// Light Palette
val AppBackgroundLight = Color(0xFFFAF7F2)
val SurfaceLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF9F1FB)
val SurfaceContainerLight = Color(0xFFF3EBF6)
val SurfaceContainerHighLight = Color(0xFFEDE6D6)
val InkLight = Color(0xFF19161D)
val MutedInkLight = Color(0xFF5B403F)
val PrimaryContainerLight = Color(0xFFDB303F)
val PrimaryFixedLight = Color(0xFFFFDAD8)
val SecondaryFixedLight = Color(0xFFE5DEFF)
val TertiaryFixedLight = Color(0xFFFFDF92)
val SecondaryContainerLight = Color(0xFF7459F7)
val AmberSparkleLight = Color(0xFFFFD152)
val CoralLight = Color(0xFFFF4B55)
val PurpleLight = Color(0xFF7B61FF)
val YellowLight = Color(0xFFFFD152)
val TealLight = Color(0xFF00C7B7)

// Dark Palette
val AppBackgroundDark = Color(0xFF121016)
val SurfaceDark = Color(0xFF1D1A21)
val SurfaceContainerLowDark = Color(0xFF26232B)
val SurfaceContainerDark = Color(0xFF2F2C36)
val SurfaceContainerHighDark = Color(0xFF3B3742)
val InkDark = Color(0xFFF6EEF9)
val MutedInkDark = Color(0xFFC7BFC8)
val PrimaryContainerDark = Color(0xFFDB303F)
val PrimaryFixedDark = Color(0xFF4A1A1E)
val SecondaryFixedDark = Color(0xFF2D1F50)
val TertiaryFixedDark = Color(0xFF423710)
val SecondaryContainerDark = Color(0xFF7459F7)
val AmberSparkleDark = Color(0xFFFFD152)
val CoralDark = Color(0xFFFF4B55)
val PurpleDark = Color(0xFF8F62FF)
val YellowDark = Color(0xFFFFD152)
val TealDark = Color(0xFF00C7B7)
